name: PR Title Check

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  validate-title:
    name: Validate PR Title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Check title format
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request.title;
            const pattern = /^:[a-z_]+: [A-Za-z-]+: [A-Za-z0-9 ,'-]+ \(#\d+\)$/;
            if (!pattern.test(title)) {
              core.setFailed(`Pull request title '${title}' does not match ':gitmoji: scope: summary (#number)' format.`);
            }
