name: Sync Labels

on:
  workflow_dispatch:
  push:
    paths:
      - .github/labels.yml

permissions:
  contents: read
  issues: write

jobs:
  sync-labels:
    name: Sync Repository Labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Apply label configuration
        uses: peter-evans/create-labels@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/labels.yml
          delete-other-labels: false
