name: Unity EditMode Comment

on:
  workflow_run:
    workflows:
      - Unity EditMode Suite
    types:
      - completed

permissions:
  issues: write
  contents: read

jobs:
  comment-result:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    steps:
      - name: Post summary to PRs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const run = context.payload.workflow_run;
            const prs = run.pull_requests || [];
            if (prs.length === 0) {
              core.info('No pull requests associated with this run.');
              return;
            }

            const status = run.conclusion === 'success' ? 'PASS' : 'FAIL';
            const body = `<!-- unity-editmode-suite -->\n### Unity EditMode Suite\nStatus: **${status}**\n- Workflow: [View Run](${run.html_url})\n- Artifacts: \`editmode-suite\``;

            for (const pr of prs) {
              const {number} = pr;
              const existing = await github.paginate(github.rest.issues.listComments, {
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: number,
              }, (response) => response.data
              ).then(comments => comments.find(comment => comment.body && comment.body.includes('<!-- unity-editmode-suite -->')));

              if (existing) {
                await github.rest.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: existing.id,
                  body,
                });
              } else {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: number,
                  body,
                });
              }
            }
